version: "3.8"
services:
  #
  # Jenkins - server for automation
  #
  jenkins:
    build:
      context: .
      dockerfile:   Dockerfile
    container_name: jenkins
    user: tcuser
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    volumes:
      - jenkins_home:/var/jenkins_home
    depends_on:
      - gitea
    networks:
      - cicd

  #
  # Gitea - server for git
  #
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__server__ROOT_URL=http://gitea:3000
      - GITEA__server__SSH_DOMAIN=gitea
      - GITEA__server__SSH_PORT=222
    ports:
      - "3000:3000"
      - "222:22"
    volumes:
      - gitea_data:/data
    networks:
      - cicd

  #
  # OpenLDAP - LDAP Server
  #
  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    restart: unless-stopped
    environment:
      LDAP_ORGANISATION:   "BPER"
      LDAP_DOMAIN:         "gbbper.it"
      LDAP_ADMIN_PASSWORD: "admin"
    ports:
      - "8082:389"
    networks:
      - cicd

  #
  # PHP LDAP ADMIN - LDAP Client
  #
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    restart: unless-stopped
    depends_on:
      - ldap
    ports:
      - "8083:80"
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS:      "false"
    networks:
      - cicd
#
# Define volumes
#
volumes:
  jenkins_home:
  gitea_data:
  # ldap_data:
  # ldap_config:

#
# Define network
#
networks:
  cicd:
    driver: bridge